# 多核CPU 自动设置工作进程数
worker_processes auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    # 定义后端服务集群
    upstream backend_servers {
        # 核心修改：使用 ip_hash
        ip_hash;

        # 两个服务器实例
        server gd-cors-app-1:8080;
        server gd-cors-app-2:8080;
    }

    # # 定义后端服务集群
    #     upstream backend_servers {
    #         # 使用客户端IP + 完整请求URI 进行 Hash
    #         # $remote_addr 是 IP，$request_uri 是 IP 之后的所有路径和参数
    #         hash "$remote_addr$request_uri" consistent;

    #         # 两个服务器实例
    #         server gd-cors-app-1:8080;
    #         server gd-cors-app-2:8080;
    # }

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/v1/ {
            client_max_body_size 1000m;

            # 对接负载均衡池
            proxy_pass http://backend_servers;

            proxy_http_version 1.1;
            proxy_set_header Connection '';
            proxy_buffering off;
            add_header X-Accel-Buffering no;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # 容错
            proxy_next_upstream error timeout;
            proxy_next_upstream_tries 2;
        }
    }
}
