# 多核CPU 自动设置工作进程数
worker_processes auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    # 定义后端服务集群（负载均衡池）
    upstream backend_servers {
        server rag-gdgs-app:8080;
        # least_conn;     # 最少连接
        # ip_hash;        # 会话保持（同一 IP 固定到同一后端）
        # weight=2;       # 权重（如 server xxx weight=2;）
    }

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/v1/ {
            client_max_body_size 1000m

            # 对接负载均衡池
            proxy_pass http://backend_servers;

            proxy_http_version 1.1;
            proxy_set_header Connection '';
            proxy_buffering off;
            add_header X-Accel-Buffering no;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
