gd-cors:
  # ============================================
  # LangChain4j 配置
  # ============================================
  langchain4j:
    open-ai:
      model:
         zhipu-api-key: ${LANGCHAIN4J_OPENAI_ONLINE_MODEL_ZHIPU_API_KEY:}
         # qwen-api-key: ${LANGCHAIN4J_OPENAI_ONLINE_MODEL_ZHIPU_API_KEY:}
    web-search-engine:
      tavily:
        api-key: ${LANGCHAIN4J_TAVILY_API_KEY:} # 从环境变量读取API Key












