events {
    worker_connections 1024;
}

http {

    # --- 日志配置 ---
    # 关闭正常的访问日志
    access_log off;
    # 错误日志存放到容器内的标准目录（只记录 warn 级别以上的错误）
    error_log /var/log/nginx/error.log warn;

    # 定义上游的 3 个 Ollama Chat 实例
    upstream ollama_chat_cluster {
        # 轮询分发 (Round Robin)
        server host.docker.internal:11431;
        server host.docker.internal:11432;
        server host.docker.internal:11433;
    }

    server {
            # Nginx 监听 11434 端口
            listen 11434;

            location / {
                proxy_pass http://ollama_chat_cluster;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;

                # --- 大模型流式输出（SSE）防卡顿 ---

                # 1. 禁用反向代理缓冲（最基础）
                proxy_buffering off;

                # 2. 禁用客户端请求缓冲
                proxy_request_buffering off;

                # 3. 强制关闭 Nginx 内部的 TCP Nagle 算法，只要有一个字节立刻发送，绝不等待合并！
                tcp_nodelay on;

                # 4. 支持 HTTP/1.1 长连接（SSE 必须基于 HTTP/1.1，而 Nginx proxy 默认是用 1.0）
                proxy_http_version 1.1;
                proxy_set_header Connection "";

                # 5. 取消对分块响应的缓存
                chunked_transfer_encoding on;

                # 6. 超时时间
                proxy_read_timeout 300s;
            }
        }
}